[icon]
[[icon.dirs]]
name = '.config'
text = ''

[[icon.dirs]]
name = '.git'
text = ''

[[icon.dirs]]
name = '.github'
text = ''

[[icon.dirs]]
name = 'desktop'
text = ''

[[icon.dirs]]
name = 'documents'
text = ''

[[icon.dirs]]
name = 'downloads'
text = ''

[[icon.dirs]]
name = 'music'
text = ''

[[icon.dirs]]
name = 'pictures'
text = ''

[[icon.dirs]]
name = 'projects'
text = '󰊢'

[[icon.dirs]]
name = 'public'
text = ''

[[icon.dirs]]
name = 'templates'
text = ''

[[icon.dirs]]
name = 'videos'
text = ''

[[icon.prepend_conds]]
fg = 'blue'
if = 'dir'
text = ''

[indicator]
[indicator.padding]
close = '█'
open = '█'

