[mgr]
ratio = [10, 25, 16]
scrolloff = 5
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_dir_first = true
sort_sensitive = true

[preview]
image_filter = "lanczos3"
tab_size = 3
wrap = "no"

[opener]
firefox = [
  { run = "firefox %s", orphan = true, desc = "Firefox" },
]
inkscape = [
  { run = "inkscape %s", orphan = true, desc = "Inkscape" },
]
gimp = [
  { run = "gimp %s", orphan = true, desc = "Gimp" },
]
kdenlive = [
  { run = "kdenlive %s", orphan = true, desc = "Kdenlive" },
]
vimiv = [
  { run = "vimiv %s", orphan = true, desc = "Vimiv" },
]
vlc = [
  { run = "vlc %s", orphan = true, desc = "Vlc" },
]
libreoffice = [
  { run = "libreoffice %s", orphan = true, desc = "Libreoffice" },
]
zathura = [
  { run = "zathura %s", orphan = true, desc = "Zathura" },
]
nvim = [
  { run = "$EDITOR %s", block = true, desc = "NeoVim" },
]
extract = [
  { run = "ya pub extract --list %s", desc = "Extract here" },
]
download = [
  { run = "ya emit download --open %S", desc = "Download and open" },
  { run = "ya emit download %S", desc = "Download" },
]

[open]
# how to get MIME type : https://mimetype.io/all-types
rules = [
  { mime = "text/*", use = "nvim" },
  { mime = "image/*", use = ["vimiv", "gimp", "inkscape"] },
  { mime = "video/*", use = ["vlc", "kdenlive"] },
  { mime = "audio/*", use = ["vlc", "kdenlive"] },
  { mime = "application/json", use = "nvim" },
  { mime = "application/pdf", use = ["zathura", "firefox", "inkscape"] },
  { mime = "application/{zip}", use = "extract" },
  { mime = "application/*", use = "libreoffice" },
  { mime = "vfs/{absent,stale}", use = "download" },  # Virtual file system
  { url = "*", use = "nvim" },
  { url = "*/", use = "nvim" },
]

[plugin]
prepend_fetchers = [
  { group = "git", run = "git", url = "*" },
  { group = "git", run = "git", url = "*/" },
]
