[mgr]
ratio = [10, 25, 16]
scrolloff = 5
show_hidden = true
show_symlink = true
sort_by = 'natural'
sort_dir_first = true
sort_sensitive = true

[preview]
image_filter = 'lanczos3'
tab_size = 3
wrap = 'no'

[plugin]
prepend_fetchers = [
   {id = 'git', run = 'git', url = '*'},
   {id = 'git', run = 'git', url = '*/'},
]
