[mgr]
ratio = [10, 25, 16]
scrolloff = 5
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_dir_first = true
sort_sensitive = true

[preview]
image_filter = "lanczos3"
tab_size = 3
wrap = "no"

[opener]
firefox = [
  { run = "firefox %s", orphan = true, desc = "Firefox", for = "linux" },
]
inkscape = [
  { run = "inkscape %s", orphan = true, desc = "Inkscape", for = "linux" },
]
gimp = [
  { run = "gimp %s", orphan = true, desc = "Gimp", for = "linux" },
]
kdenlive = [
  { run = "kdenlive %s", orphan = true, desc = "Kdenlive", for = "linux" },
]
vlc = [
  { run = "vlc %s", orphan = true, desc = "Vlc", for = "linux" },
]
libreoffice = [
  { run = "libreoffice %s", orphan = true, desc = "Libreoffice", for = "linux" },
]
nvim = [
  { run = "$EDITOR %s", block = true, desc = "Nvim", for = "linux" },
]

[open]
# how to get MIME type : https://mimetype.io/all-types
rules = [
  { url = "*.docx", use = "libreoffice" },
  { mime = "application/pdf", use = ["firefox", "inkscape"] },
  { mime = "image/*", use = ["gimp", "inkscape"] },
  { mime = "video/*", use = ["vlc", "kdenlive"] },
  { mime = "*", use = "nvim" }
]

[plugin]
prepend_fetchers = [
  { id = "git", run = "git", url = "*" },
  { id = "git", run = "git", url = "*/" },
]
