# [[ OUTPUTS ]]
monitorrule=name:DP-1,    rr:0,scale:1,x:1080,y:688,width:1920,height:1080,refresh:60
monitorrule=name:HDMI-A-1,rr:1,scale:1,x:0,   y:0  ,width:1920,height:1080,refresh:60

tagrule=id:1,monitor_name:HDMI-A-1,layout_name:vertical_scroller
tagrule=id:2,monitor_name:HDMI-A-1,layout_name:vertical_scroller
tagrule=id:3,monitor_name:HDMI-A-1,layout_name:vertical_scroller
tagrule=id:4,monitor_name:HDMI-A-1,layout_name:vertical_scroller
tagrule=id:5,monitor_name:HDMI-A-1,layout_name:vertical_scroller
tagrule=id:6,monitor_name:HDMI-A-1,layout_name:vertical_scroller
tagrule=id:7,monitor_name:HDMI-A-1,layout_name:vertical_scroller
tagrule=id:8,monitor_name:HDMI-A-1,layout_name:vertical_scroller
tagrule=id:9,monitor_name:HDMI-A-1,layout_name:vertical_scroller
