#!/usr/bin/env bash
#000000
#C0C0C0ff
#F9F9FA33
#008080

if [[ -z $1 ]]; then
	mkdir -p "$GRIM_DEFAULT_DIR"
	grim -g "$(slurp -b '#F9F9FA33' -c '#C0C0C0ff')"
elif [[ $1 == "copy" ]]; then
	grim -g "$(slurp -b '#F9F9FA33' -c '#C0C0C0ff')" - | wl-copy
elif [[ $1 == "color" ]]; then
	slurp -p | grim -g - - | magick - txt: | awk 'NR==2 { print $3 }' | wl-copy
fi
