# TODO: https://mangowc.vercel.app/docs/bindings/mouse-gestures#switch-bindings-lid

# [[ KEYBINDS ]]
# https://github.com/DreamMaoMao/mangowc/wiki#key-bindings

# misc
bind=SUPER,f,togglefullscreen,
bind=SUPER,space,togglefloating,

bind=super,t,spawn,~/.config/mango/scripts/toggle-monitor.sh "HDMI-A-1"
# bind=super,r,spawn,~/.config/mango/scripts/toggle-monitor.sh "DP-1" # useless

bind=super,w,spawn,~/.config/waybar/scripts/toggle_waybar

# utilities
bind=SUPER+SHIFT,q,killclient,

bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl set +5%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl set 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 2.5%-
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 2.5%+
bind=NONE,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bind=SUPER,c,spawn,~/.config/mango/scripts/color_picker.sh
bind=SUPER,s,spawn,~/.config/mango/scripts/screenshoot.sh
bind=SUPER,y,spawn,~/.config/mango/scripts/screenshoot_yank.sh

# apps
bind=SUPER,Return,spawn,kitty --hold fastfetch
bind=SUPER,b,spawn,firefox

bind=SUPER,d,spawn,wofi


# movement
bind=SUPER,h,focusdir,left
bind=SUPER,j,focusdir,down
bind=SUPER,k,focusdir,up
bind=SUPER,l,focusdir,right

bind=SUPER,n,focusstack,next
bind=SUPER,p,focusstack,prev

bind=SUPER,0,view,0
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9

bind=SUPER+CTRL,h,focusmon,left
bind=SUPER+CTRL,j,focusmon,down
bind=SUPER+CTRL,k,focusmon,up
bind=SUPER+CTRL,l,focusmon,right

# move window
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,l,exchange_client,right

bind=SUPER+SHIFT,n,exchange_stack_client,next
bind=SUPER+SHIFT,p,exchange_stack_client,prev

bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9

bind=SUPER+CTRL+SHIFT,h,tagmon,left
bind=SUPER+CTRL+SHIFT,j,tagmon,down
bind=SUPER+CTRL+SHIFT,k,tagmon,up
bind=SUPER+CTRL+SHIFT,l,tagmon,right

mousebind=SUPER,btn_left,moveresize,curmove # Move window
mousebind=SUPER,btn_right,moveresize,curresize # Resize window

# scratchpad
# music scratchpad
#    MOD,  KEY,toggle_named_scratchpad,appid,         title,command
bind=SUPER,m,  toggle_named_scratchpad,deezer-desktop,none, deezer-desktop > /dev/null 2>&1 &

# key modes
bind=SUPER,r,setkeymode,resize

keymode=resize
bind=NONE,h,resizewin,-10,+0
bind=NONE,j,resizewin,+0,+10
bind=NONE,k,resizewin,+0,-10
bind=NONE,l,resizewin,+10,+0
bind=SHIFT,h,movewin,-10,+0
bind=SHIFT,j,movewin,+0,+10
bind=SHIFT,k,movewin,+0,-10
bind=SHIFT,l,movewin,+10,+0
bind=NONE,space,centerwin
bind=NONE,Escape,setkeymode,default




