# [[ KEYBINDS ]]

# misc
bind=SUPER,f,togglefullscreen,
bind=SUPER+SHIFT,f,togglefakefullscreen,
bind=SUPER,space,togglefloating,

bind=super,w,spawn,$NIXOS_CONFIG_DIR/dotfiles/scripts/bar_controls toggle

# utilities
bind=SUPER+SHIFT,q,killclient,

bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl set +5%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl set 5%-
bind=NONE,XF86AudioMute,spawn,$NIXOS_CONFIG_DIR/dotfiles/scripts/volume mute
bind=NONE,XF86AudioLowerVolume,spawn,$NIXOS_CONFIG_DIR/dotfiles/scripts/volume down
bind=NONE,XF86AudioRaiseVolume,spawn,$NIXOS_CONFIG_DIR/dotfiles/scripts/volume up
bind=NONE,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bind=SUPER,s,spawn,$XDG_CONFIG_HOME/scripts/screenshoot
bind=SUPER,y,spawn,$XDG_CONFIG_HOME/scripts/screenshoot copy
bind=SUPER,c,spawn,$XDG_CONFIG_HOME/scripts/screenshoot color

# apps
bind=SUPER,Return,spawn,kitty --hold $NIXOS_CONFIG_DIR/dotfiles/scripts/run_cmd fastfetch
bind=SUPER,b,spawn,firefox

bind=SUPER,d,spawn,wofi

bind=SUPER,m,toggle_named_scratchpad,deezer-desktop,none,deezer-desktop > /dev/null 2>&1 &

# movement
bind=SUPER,h,focusdir,left
bind=SUPER,j,focusdir,down
bind=SUPER,k,focusdir,up
bind=SUPER,l,focusdir,right

bind=SUPER,n,focusstack,next
bind=SUPER,p,focusstack,prev

bind=SUPER,0,view,0
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9

bind=SUPER+CTRL,h,focusmon,left
bind=SUPER+CTRL,j,focusmon,down
bind=SUPER+CTRL,k,focusmon,up
bind=SUPER+CTRL,l,focusmon,right

# move window
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,l,exchange_client,right

bind=SUPER+SHIFT,n,exchange_stack_client,next
bind=SUPER+SHIFT,p,exchange_stack_client,prev

bind=SUPER+SHIFT,1,tagsilent,1
bind=SUPER+SHIFT,2,tagsilent,2
bind=SUPER+SHIFT,3,tagsilent,3
bind=SUPER+SHIFT,4,tagsilent,4
bind=SUPER+SHIFT,5,tagsilent,5
bind=SUPER+SHIFT,6,tagsilent,6
bind=SUPER+SHIFT,7,tagsilent,7
bind=SUPER+SHIFT,8,tagsilent,8
bind=SUPER+SHIFT,9,tagsilent,9

bind=SUPER+CTRL+SHIFT,h,tagmon,left
bind=SUPER+CTRL+SHIFT,j,tagmon,down
bind=SUPER+CTRL+SHIFT,k,tagmon,up
bind=SUPER+CTRL+SHIFT,l,tagmon,right

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# key modes
bind=SUPER,r,setkeymode,resize

keymode=resize
bind=NONE,h,resizewin,-10,+0
bind=NONE,j,resizewin,+0,+10
bind=NONE,k,resizewin,+0,-10
bind=NONE,l,resizewin,+10,+0
bind=SHIFT,h,movewin,-10,+0
bind=SHIFT,j,movewin,+0,+10
bind=SHIFT,k,movewin,+0,-10
bind=SHIFT,l,movewin,+10,+0
bind=NONE,space,centerwin
bind=NONE,Escape,setkeymode,default




