# [[ RULES ]]

# [[ SETTINGS ]]
enable_hotarea = 0 # disable overview
drag_tile_to_tile = 1
cursor_hide_timeout = 5
view_current_to_back = 0

scratchpad_width_ratio = 0.8
scratchpad_height_ratio = 0.8
scratchpad_cross_monitor = 1 # monitors have the same scratchpad

repeat_rate = 25
repeat_delay = 300

middle_button_emulation = 1 # enable middle button on trackpad

# [[ MONITORS ]]

# [[ WINDOWS ]]
windowrule=isnamedscratchpad:1,title:filechooser
# windowrule=isnamedscratchpad:1,appid:electron TODO: add back with height and width ratio parameter https://github.com/mangowm/mango/issues/552

# [[ LAYER ]]
layerrule=layer_name:wofi,noanim:1

# [[ TAGS ]]
tagrule=id:0,monitor_name:DP-1,layout_name:scroller

# [[ MASTER-STACK CONF ]]
new_is_master = 1
default_mfact = 0.5
smartgaps = 0
center_master_overspread = 1

# [[ SCROLLER CONF ]]
scroller_default_proportion = 0.5
scroller_prefer_overspread = 1
scroller_focus_center = 0
scroller_prefer_center = 1
scroller_ignore_proportion_single = 0
scroller_default_proportion_single = 1.0
edge_scroller_pointer_focus = 0



