#!/usr/bin/env bash
# notify
swaync &> /dev/null &

# blue light filter
sunsetr &> /dev/null &

# bar
"$XDG_CONFIG_HOME/scripts/bar_controls" open &> /dev/null &

# wallpaper
"$XDG_CONFIG_HOME/scripts/pscircle_bg" &> /dev/null &

# start tmux
"$XDG_CONFIG_HOME/scripts/tmux-session-dispensary" "$HOME" &> /dev/null &

if [[ $(hostname) == "nixos-main" ]]; then
	mmsg dispatch focusmon,"HDMI-A-1" &> /dev/null
	mmsg dispatch view,9 &> /dev/null
	mmsg dispatch toggle_named_scratchpad,dev.aunetx.deezer,none,deezer-desktop &> /dev/null &
	firefox &> /dev/null &
elif [[ $(hostname) == "nixos-school" ]]; then
	mmsg dispatch focusmon,"eDP-1" &> /dev/null
	mmsg dispatch view,9 &> /dev/null
	firefox &> /dev/null &
fi

# remove trash files older than 100 days
find "$XDG_DATA_HOME/Trash" -type f -atime +100 -exec rm {} \; &> /dev/null &
